services:
    quake-server:
        platform: linux/i386
        restart: always
        stop_grace_period: 0s
        stdin_open: true
        tty: true
        build:
            context: ../Quake-LinuxUpdate
            dockerfile: ./Dockerfile
        ports:
            - 26000:26000/tcp
            - 26000:26000/udp
            - 7072:7072/tcp

    websocket-proxy:
        restart: always
        stop_grace_period: 0s
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 7071:7071/tcp

    quake-wasm:
        restart: always
        stop_grace_period: 0s
        build:
            context: ../Quake-WASM
            dockerfile: ./Dockerfile
        ports:
            - 7070:80/tcp
